---
- name: Install yay
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - yay
        - yay:install
  when:
    - install | default(true) | bool
    - ansible_facts.get('os_family') == 'Archlinux'
  tags:
    - yay
    - yay:install

- name: Uninstall yay
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - yay
        - yay:uninstall
  when:
    - not (install | default(true) | bool)
    - ansible_facts.get('os_family') == 'Archlinux'
  tags:
    - yay
    - yay:uninstall
