---
- name: Uninstall yay
  become: true
  community.general.pacman:
    name: yay
    state: absent
  when: ansible_os_family == 'Archlinux'

- name: Cleanup /tmp/yay
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
  when: ansible_os_family == 'Archlinux'
